services:
  gamesdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5005:5432
