CREATE TABLE IF NOT EXISTS users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(512) UNIQUE NOT NULL,
    username varchar(64) UNIQUE NOT NULL,
    picture varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS apps (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    appid int UNIQUE NOT NULL,
    title varchar(512) UNIQUE NOT NULL,
    synopsis text NOT NULL,  
    image_url varchar(1024)
);

CREATE TABLE IF NOT EXISTS reviews (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reviewer_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamp NOT NULL DEFAULT current_timestamp(3), -- YYYY-MM-DD HH:mm:ss.sssZZ where ZZ is timezone hour
    title varchar(512) NOT NULL,
    content varchar(1024) NOT NULL,
    rating smallint NOT NULL,
    appid int NOT NULL REFERENCES apps(appid) ON DELETE CASCADE
);
