CREATE TABLE IF NOT EXISTS users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(512) UNIQUE NOT NULL,
    username varchar(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reviewer_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamp NOT NULL DEFAULT current_timestamp,
    content varchar(1024) NOT NULL
);